version: 2
jobs:
  build:
    working_directory: ~/ngx-typeahead
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: plugin-build
          command: yarn build --no-progress
      - run:
          name: plugin-test
          command: yarn test -- --single-run --no-progress
